### ISSUE TITLE
Using sample-sources instead of device_notify_map

### ISSUE THREAD

**Issue by Jokeren** [aarontcopal2/hpctoolkit#1]
https://github.com/aarontcopal2/hpctoolkit/blob/e42dc086979d1d0b381db976663917885022cc9a/src/tool/hpcrun/gpu/intel/opencl-api.c#L21

`correlation_id` should be increased and read atomically.

https://github.com/aarontcopal2/hpctoolkit/blob/e42dc086979d1d0b381db976663917885022cc9a/src/tool/hpcrun/gpu/intel/opencl-activity-translate.c#L39

Check if you can or cannot find the corresponding node.

https://github.com/aarontcopal2/hpctoolkit/blob/e42dc086979d1d0b381db976663917885022cc9a/src/tool/hpcrun/gpu/intel/opencl-setup.c#L37

Where this function is called?

**Comment by aarontcopal2** [comment]
1.  I am doing atomic increments, I thought that would be enough. I'll make the change for atomic reads.
https://github.com/aarontcopal2/hpctoolkit/blob/e42dc086979d1d0b381db976663917885022cc9a/src/tool/hpcrun/gpu/intel/opencl-api.c#L45

2. Yes, I checked this while debugging. I am getting the node over here.

3. This is where checkIfOpenCLModuleLoadedAndSetIntercepts is called from:
https://github.com/aarontcopal2/hpctoolkit/blob/8b92e780f95dae42df56834aa6e3693c00d14739/src/tool/hpcrun/device-initializers.c#L15

**Comment by Jokeren** [comment]
> 1. I am doing atomic increments, I thought that would be enough. I'll make the change for atomic reads.
>    https://github.com/aarontcopal2/hpctoolkit/blob/e42dc086979d1d0b381db976663917885022cc9a/src/tool/hpcrun/gpu/intel/opencl-api.c#L45

The thing is, even if you use a separate atomic read, the code here is still wrong. What you have to use is something like `correlation_id_local = __atomic_fetch_add(&correlation_id, 1, __ATOMIC_SEQ_CST)`, which reads and writes simultaneously.
 
> 2. Yes, I checked this while debugging. I am getting the node over here.
> 3. This is where checkIfOpenCLModuleLoadedAndSetIntercepts is called from:
>    https://github.com/aarontcopal2/hpctoolkit/blob/8b92e780f95dae42df56834aa6e3693c00d14739/src/tool/hpcrun/device-initializers.c#L15

I am confused. Who let you call this function in that file? The function `device_notify_map` will be called every time a new library is opened. Why not create a `intel.c` under `sample-sources`

**Comment by aarontcopal2** [comment]
Ill make these changes. But this still does'nt explain why metrics are not showing up

**Comment by Jokeren** [comment]
May or may not.

https://github.com/aarontcopal2/hpctoolkit/blob/e42dc086979d1d0b381db976663917885022cc9a/src/tool/hpcrun/gpu/intel/opencl-setup.c#L24

In the previous implementation, you may initialize gpu metrics several times.

Besides, you have to use hpcproftt to check if you truly have created gpu metrics or not.

**Comment by Jokeren** [comment]
Before trying to figure out why metrics are not showing up, fix the initialization procedure by creating a sample source file similar as `amd.c` is helpful.

**Comment by aarontcopal2** [comment]
sample-sources/opencl.c has been created. All metrics are now visible
