### ISSUE TITLE
Missing gpu_metrics in opencl hpcrun

### ISSUE THREAD

**Issue by aarontcopal2** [aarontcopal2/hpctoolkit#3]
GPU metrics are missing from cct's. This could be because the background thread and not main thread's is storing the gpu_metrics value. To fix this, we need to change where some functions are called from.
@Jokeren , is the below list correct?

**Main thread**
1. gpu_activity_channel_consume(gpu_metrics_attribute);
2. gpu_activity_channel_produce(channel, activity);
3. gpu_correlation_channel_consume
4. gpu_correlation_channel_produce

**Background thread**
1. gpu_correlation_id_map_insert
2. gpu_correlation_id_map_lookup
3. gpu_correlation_id_map_entry_external_id_get
4. gpu_host_correlation_map_lookup
5. gpu_host_correlation_map_entry_op_cct_get

**Comment by Jokeren** [comment]
**Main thread**

gpu_activity_channel_consume(gpu_metrics_attribute);
gpu_correlation_channel_produce

**Background thread**

gpu_activity_channel_produce(channel, activity);
gpu_correlation_channel_consume
gpu_correlation_id_map_insert
gpu_correlation_id_map_lookup
gpu_correlation_id_map_entry_external_id_get
gpu_host_correlation_map_lookup
gpu_host_correlation_map_entry_op_cct_get

**Comment by aarontcopal2** [comment]
These changes are made in commit 716d45c2fa6a28. GPU metrics are now visible
